### PR TITLE
#146687391 Stabilise base application

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
This will ensure that the application can be run seamlessly when a team member clones the repo.
#### Description of Task to be completed?
Nil
#### How should this be manually tested?
Run npm install to install new dependencies added
Create a .env file in your root directory request for its content from me. 
Run npm start to start the application. 
#### Any background context you want to provide?
Nil
#### What are the relevant pivotal tracker stories?
Nil
#### Screenshots (if appropriate)
Nil
#### Questions:
Nil

### CODE REVIEW

**Comment by q-ode** [comment]
I'm sure this doesn't look anything like the PR Naming Convention you were given. Please address.

**Comment by ghost** [comment]
I have made changes based on what I read in the document shared https://github.com/andela/temari-rc/wiki/Pull-Request-Naming-and-Description-Convention

**Comment by q-ode** [comment]
Did you see the description?

**Comment by ghost** [comment]
I just followed the description now. Is this okay?

**Pull request merged**
